import type { VisitNote } from "@nfc/contracts";
import { and,eq } from "drizzle-orm";
import type { Database } from "../db/client.js";
import { appointmentEvents,appointments,doctors,visitNotes } from "../db/schema/index.js";
import { ApiError } from "../http/api-error.js";
import type { VisitNoteService } from "./visit-note-types.js";
function output(row:{id:string;appointmentId:string;content:string;createdAt:Date}):VisitNote{return {id:row.id,appointmentId:row.appointmentId,note:row.content,createdAt:row.createdAt.toISOString()};}
function conflict(error:unknown):never{const code=typeof error==="object"&&error&&"code" in error?String(error.code):"";if(code==="23505")throw new ApiError(409,"VISIT_NOTE_ALREADY_EXISTS","A visit note already exists for this appointment.");throw error;}
export function createVisitNoteService(database:Database):VisitNoteService{return {
  async createForDoctor(profileId,appointmentId,input){try{return await database.transaction(async tx=>{const [appointment]=await tx.select({id:appointments.id,doctorId:appointments.doctorId,patientId:appointments.patientId,status:appointments.status}).from(appointments).innerJoin(doctors,eq(appointments.doctorId,doctors.id)).where(and(eq(appointments.id,appointmentId),eq(doctors.profileId,profileId),eq(doctors.isActive,true))).limit(1).for("update");if(!appointment)throw new ApiError(404,"NOT_FOUND","Appointment was not found.");if(appointment.status!=="COMPLETED")throw new ApiError(409,"VISIT_NOTE_NOT_ALLOWED","A visit note can only be added after the appointment is completed.");const [created]=await tx.insert(visitNotes).values({appointmentId,doctorId:appointment.doctorId,patientId:appointment.patientId,content:input.note}).returning({id:visitNotes.id,appointmentId:visitNotes.appointmentId,content:visitNotes.content,createdAt:visitNotes.createdAt});await tx.insert(appointmentEvents).values({appointmentId,eventType:"VISIT_NOTE_CREATED",fromStatus:"COMPLETED",toStatus:"COMPLETED",actorProfileId:profileId,metadata:{visitNoteId:created!.id}});return output(created!);});}catch(error){if(error instanceof ApiError)throw error;conflict(error);}},
  async getForDoctor(profileId,appointmentId){const [row]=await database.select({id:visitNotes.id,appointmentId:visitNotes.appointmentId,content:visitNotes.content,createdAt:visitNotes.createdAt}).from(appointments).innerJoin(doctors,eq(appointments.doctorId,doctors.id)).leftJoin(visitNotes,eq(visitNotes.appointmentId,appointments.id)).where(and(eq(appointments.id,appointmentId),eq(doctors.profileId,profileId),eq(doctors.isActive,true))).limit(1);if(!row)throw new ApiError(404,"NOT_FOUND","Appointment was not found.");return row.id?output({...row,id:row.id,appointmentId:row.appointmentId!,content:row.content!,createdAt:row.createdAt!}):null;},
  async getForPatient(profileId,appointmentId){const [row]=await database.select({id:visitNotes.id,appointmentId:visitNotes.appointmentId,content:visitNotes.content,createdAt:visitNotes.createdAt}).from(appointments).leftJoin(visitNotes,eq(visitNotes.appointmentId,appointments.id)).where(and(eq(appointments.id,appointmentId),eq(appointments.patientId,profileId))).limit(1);if(!row)throw new ApiError(404,"NOT_FOUND","Appointment was not found.");return row.id?output({...row,id:row.id,appointmentId:row.appointmentId!,content:row.content!,createdAt:row.createdAt!}):null;},
};}
