import { adminAppointmentQuerySchema,adminDoctorQuerySchema,createDoctorInputSchema,updateDoctorStatusSchema,uuidSchema } from "@nfc/contracts";
import { Router,type RequestHandler } from "express";
import type { AdminService } from "../admin/types.js";
import type { ProfileRepository,TokenVerifier } from "../auth/types.js";
import { ApiError } from "../http/api-error.js";
import { success } from "../http/responses.js";
import { createRequireAuth,requireAdmin } from "../middleware/auth.js";
function asyncRoute(handler:RequestHandler):RequestHandler{return async(req,res,next)=>{try{await handler(req,res,next);}catch(error){next(error);}};}
function parse<T>(schema:{safeParse(value:unknown):{success:true;data:T}|{success:false;error:{issues:Array<{path:PropertyKey[];message:string}>}}},value:unknown,message:string):T{const result=schema.safeParse(value);if(!result.success)throw new ApiError(400,"VALIDATION_ERROR",message,result.error.issues.map(issue=>({field:issue.path.join("."),message:issue.message})));return result.data;}
export function createAdminRouter(verifier:TokenVerifier,profiles:ProfileRepository,service:AdminService,webOrigin:string){const router=Router();router.use(createRequireAuth(verifier,profiles),requireAdmin);router.get("/dashboard",asyncRoute(async(_req,res)=>{res.json(success(await service.dashboard()));}));router.get("/appointments",asyncRoute(async(req,res)=>{res.json(success(await service.appointments(parse(adminAppointmentQuerySchema,req.query,"Appointment filters are invalid."))));}));router.get("/doctors",asyncRoute(async(req,res)=>{res.json(success(await service.listDoctors(parse(adminDoctorQuerySchema,req.query,"Doctor filters are invalid."))));}));router.post("/doctors",asyncRoute(async(req,res)=>{const input=parse(createDoctorInputSchema,req.body,"Doctor details are invalid.");res.status(201).json(success(await service.createDoctor(req.auth!.profile.id,input,`${webOrigin}/auth/set-password`)));}));router.patch("/doctors/:doctorId/status",asyncRoute(async(req,res)=>{const doctorId=parse(uuidSchema,req.params.doctorId,"Doctor ID is invalid.");const input=parse(updateDoctorStatusSchema,req.body,"Doctor status is invalid.");res.json(success(await service.setDoctorActive(req.auth!.profile.id,doctorId,input.isActive)));}));return router;}
