import type { AdminDashboard,AppointmentStatus } from "@nfc/contracts";
import { and,asc,count,eq,gte,ilike,lt,or,sql,type SQL } from "drizzle-orm";
import { alias } from "drizzle-orm/pg-core";
import type { Database } from "../db/client.js";
import { adminAppointmentFields } from "../db/repositories/admin-appointment-fields.js";
import { adminDoctorEvents,appointments,doctors,profiles } from "../db/schema/index.js";
import { ApiError } from "../http/api-error.js";
import { localAppointmentParts } from "../appointments/rules.js";
import { clinicDayBounds,clinicToday,CLINIC_TIMEZONE } from "../scheduling/timezone.js";
import type { AdminService,DoctorInviter } from "./types.js";
const doctorProfiles=alias(profiles,"admin_doctor_profiles"),patientProfiles=alias(profiles,"admin_patient_profiles");
const empty=()=>({total:0,pending:0,confirmed:0,completed:0,noShow:0,cancelled:0,rejected:0});
function add(target:ReturnType<typeof empty>,status:AppointmentStatus){target.total++;if(status==="PENDING")target.pending++;else if(status==="CONFIRMED")target.confirmed++;else if(status==="COMPLETED")target.completed++;else if(status==="NO_SHOW")target.noShow++;else if(status==="CANCELLED")target.cancelled++;else target.rejected++;}
export function aggregateAdminDashboard(date:string,doctorRows:{doctorId:string;doctorName:string;specialization:string}[],appointmentRows:{doctorId:string;status:AppointmentStatus}[]):AdminDashboard{const totals=empty(),byDoctor=new Map(doctorRows.map(row=>[row.doctorId,{...row,...empty()}]));for(const row of appointmentRows){add(totals,row.status);const summary=byDoctor.get(row.doctorId);if(summary)add(summary,row.status);}return {date,timezone:CLINIC_TIMEZONE,totals,doctors:[...byDoctor.values()]};}
const adminDoctorFields={id:doctors.id,profileId:doctors.profileId,fullName:profiles.fullName,email:profiles.email,phone:profiles.phone,specialization:doctors.specialization,qualifications:doctors.qualifications,experienceYears:doctors.experienceYears,consultationLocation:doctors.consultationLocation,bio:doctors.bio,isActive:doctors.isActive,createdAt:doctors.createdAt};
export function doctorProvisioningValues(userId:string,input:{fullName:string;email:string;phone:string;specialization:string;qualifications:string;experienceYears:number;consultationLocation:string;bio:string}){return {profile:{id:userId,role:"DOCTOR" as const,fullName:input.fullName,email:input.email,phone:input.phone,isActive:true},doctor:{profileId:userId,specialization:input.specialization,qualifications:input.qualifications,experienceYears:input.experienceYears,consultationLocation:input.consultationLocation,bio:input.bio,isActive:true}};}
function doctorOutput(row:typeof adminDoctorFields extends infer _T?any:never){return {...row,email:row.email??"",createdAt:row.createdAt.toISOString()};}
function conflict(error:unknown):never{const cause=(error as {cause?:{code?:string}}).cause;if(cause?.code==="23505")throw new ApiError(409,"DOCTOR_EMAIL_EXISTS","A clinic account already uses this email address.");throw error;}
export function createAdminService(database:Database,clock:()=>Date=()=>new Date(),inviter?:DoctorInviter):AdminService{return {
 async dashboard(){const date=clinicToday(clock()),bounds=clinicDayBounds(date);const [doctorRows,appointmentRows]=await Promise.all([database.select({doctorId:doctors.id,doctorName:profiles.fullName,specialization:doctors.specialization}).from(doctors).innerJoin(profiles,eq(doctors.profileId,profiles.id)).orderBy(asc(profiles.fullName)),database.select({doctorId:appointments.doctorId,status:appointments.status}).from(appointments).where(and(gte(appointments.startAt,bounds.start),lt(appointments.startAt,bounds.end)))]);return aggregateAdminDashboard(date,doctorRows,appointmentRows);},
 async appointments(query){const predicates:SQL[]=[];if(query.doctorId)predicates.push(eq(appointments.doctorId,query.doctorId));if(query.status)predicates.push(eq(appointments.status,query.status));if(query.date){const bounds=clinicDayBounds(query.date);predicates.push(gte(appointments.startAt,bounds.start),lt(appointments.startAt,bounds.end));}if(query.q)predicates.push(or(ilike(doctorProfiles.fullName,`%${query.q}%`),ilike(patientProfiles.fullName,`%${query.q}%`))!);const where=predicates.length?and(...predicates):undefined;
  const fields={...adminAppointmentFields,doctorName:doctorProfiles.fullName,doctorSpecialization:doctors.specialization,patientFullName:patientProfiles.fullName,patientPhone:patientProfiles.phone};const base=database.select(fields).from(appointments).innerJoin(doctors,eq(appointments.doctorId,doctors.id)).innerJoin(doctorProfiles,eq(doctors.profileId,doctorProfiles.id)).innerJoin(patientProfiles,eq(appointments.patientId,patientProfiles.id));const rows=await base.where(where).orderBy(asc(appointments.startAt)).limit(query.limit).offset((query.page-1)*query.limit);const [totalRow]=await database.select({value:count()}).from(appointments).innerJoin(doctors,eq(appointments.doctorId,doctors.id)).innerJoin(doctorProfiles,eq(doctors.profileId,doctorProfiles.id)).innerJoin(patientProfiles,eq(appointments.patientId,patientProfiles.id)).where(where);return {items:rows.map(row=>({id:row.id,doctor:{id:row.doctorId,fullName:row.doctorName,specialization:row.doctorSpecialization},patient:{id:row.patientId,fullName:row.patientFullName,phone:row.patientPhone},startAt:row.startAt.toISOString(),endAt:row.endAt.toISOString(),...localAppointmentParts(row.startAt,row.endAt),status:row.status,createdAt:row.createdAt.toISOString()})),page:query.page,limit:query.limit,total:totalRow?.value??0,totalPages:Math.ceil((totalRow?.value??0)/query.limit)};},
 async listDoctors(query){const where=query.q?or(ilike(profiles.fullName,`%${query.q}%`),ilike(profiles.email,`%${query.q}%`),ilike(doctors.specialization,`%${query.q}%`)):undefined;const rows=await database.select(adminDoctorFields).from(doctors).innerJoin(profiles,eq(doctors.profileId,profiles.id)).where(where).orderBy(asc(profiles.fullName));return rows.map(doctorOutput);},
 async createDoctor(actorProfileId,input,redirectTo){if(!inviter)throw new ApiError(503,"INVITATION_UNAVAILABLE","Doctor invitations are not configured.");const [existing]=await database.select({id:profiles.id}).from(profiles).where(sql`lower(${profiles.email}) = ${input.email.toLowerCase()}`).limit(1);if(existing)throw new ApiError(409,"DOCTOR_EMAIL_EXISTS","A clinic account already uses this email address.");let userId:string|undefined;try{userId=(await inviter.invite(input.email,redirectTo,{fullName:input.fullName,phone:input.phone})).userId;const values=doctorProvisioningValues(userId,input);const created=await database.transaction(async tx=>{await tx.insert(profiles).values(values.profile).onConflictDoUpdate({target:profiles.id,set:{role:"DOCTOR",fullName:input.fullName,email:input.email,phone:input.phone,isActive:true}});const [inserted]=await tx.insert(doctors).values(values.doctor).returning({id:doctors.id});await tx.insert(adminDoctorEvents).values({doctorId:inserted!.id,actorProfileId,eventType:"DOCTOR_INVITED",metadata:{email:input.email}});const [doctor]=await tx.select(adminDoctorFields).from(doctors).innerJoin(profiles,eq(doctors.profileId,profiles.id)).where(eq(doctors.id,inserted!.id)).limit(1);return doctorOutput(doctor!);});return created;}catch(error){if(userId){await inviter.deleteUser(userId).catch(()=>undefined);await database.delete(profiles).where(eq(profiles.id,userId)).catch(()=>undefined);}conflict(error);}},
 async setDoctorActive(actorProfileId,doctorId,isActive){const result=await database.transaction(async tx=>{const [current]=await tx.select({id:doctors.id,profileId:doctors.profileId}).from(doctors).where(eq(doctors.id,doctorId)).limit(1).for("update");if(!current)throw new ApiError(404,"NOT_FOUND","Doctor was not found.");await tx.update(doctors).set({isActive}).where(eq(doctors.id,doctorId));await tx.update(profiles).set({isActive}).where(eq(profiles.id,current.profileId));await tx.insert(adminDoctorEvents).values({doctorId,actorProfileId,eventType:isActive?"DOCTOR_ACTIVATED":"DOCTOR_DEACTIVATED"});const [row]=await tx.select(adminDoctorFields).from(doctors).innerJoin(profiles,eq(doctors.profileId,profiles.id)).where(eq(doctors.id,doctorId)).limit(1);return doctorOutput(row!);});return result;}
};}
