import type { PatientAppointment } from "@nfc/contracts";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, CalendarDays, MapPin, RotateCcw, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../features/auth/auth-provider";
import { ApiClientError, appointmentApi, schedulingApi } from "../lib/api";
import { clinicToday } from "../lib/clinic-time";

type Filter="upcoming"|"history"|"all";
const active=(item:PatientAppointment)=>["PENDING","CONFIRMED"].includes(item.status)&&new Date(item.startAt)>new Date();
const statusLabel=(status:string)=>status==="NO_SHOW"?"No-show":status.charAt(0)+status.slice(1).toLowerCase();

export function PatientAppointmentsPage({ historyOnly=false }: { historyOnly?: boolean }) {
  const {session}=useAuth();const client=useQueryClient();const [filter,setFilter]=useState<Filter>(historyOnly?"history":"upcoming");const [rescheduling,setRescheduling]=useState<PatientAppointment|null>(null);const [date,setDate]=useState(clinicToday());const [slot,setSlot]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
  const query=useQuery({queryKey:["patient-appointments"],queryFn:()=>appointmentApi.list(session!.access_token),enabled:Boolean(session)});
  const availability=useQuery({queryKey:["availability",rescheduling?.doctor.id,date],queryFn:()=>schedulingApi.availability(session!.access_token,rescheduling!.doctor.id,date),enabled:Boolean(session&&rescheduling&&date)});
  const cancel=useMutation({mutationFn:(id:string)=>appointmentApi.cancel(session!.access_token,id),onSuccess:async(item)=>{setNotice("Appointment cancelled. The slot is available again.");await Promise.all([client.invalidateQueries({queryKey:["patient-appointments"]}),client.invalidateQueries({queryKey:["availability",item.doctor.id]} )]);}});
  const move=useMutation({mutationFn:()=>{if(!rescheduling||!slot)throw new Error("Choose a new slot.");return appointmentApi.reschedule(session!.access_token,rescheduling.id,{date,startTime:slot});},onSuccess:async(item)=>{setNotice("Appointment rescheduled and returned to Pending.");setRescheduling(null);setSlot(null);await Promise.all([client.invalidateQueries({queryKey:["patient-appointments"]}),client.invalidateQueries({queryKey:["availability",item.doctor.id]})]);},onError:async(error)=>{if(error instanceof ApiClientError&&error.status===409){setNotice(error.message);setSlot(null);await client.invalidateQueries({queryKey:["availability",rescheduling?.doctor.id,date]});}}});
  const items=(query.data??[]).filter(item=>filter==="all"?true:filter==="upcoming"?active(item):!active(item));
  return <div><div className="portal-title"><div><p><CalendarClock size={14}/> Your care timeline</p><h1>{historyOnly?"Appointment history":"My appointments"}</h1><span>Manage upcoming requests and keep a clear record of previous visits.</span></div></div>
    {!historyOnly&&<div className="appointment-tabs">{(["upcoming","history","all"] as Filter[]).map(value=><button className={filter===value?"active":""} onClick={()=>setFilter(value)} key={value}>{value}</button>)}</div>}
    {notice&&<div className="success-note">{notice}</div>}{query.isLoading&&<div className="state-card">Loading your appointments…</div>}{query.isError&&<div className="form-alert">Appointments could not be loaded.</div>}
    {!query.isLoading&&items.length===0&&<div className="state-card"><CalendarDays/><h2>No appointments here</h2><p>{filter==="upcoming"?"Choose a doctor and request a time that suits you.":"Your completed and cancelled appointments will remain here."}</p><Link className="button button-primary" to="/patient/doctors">Find a doctor</Link></div>}
    <div className="appointment-list">{items.map(item=><article className="appointment-card glass-panel" key={item.id}><div className="appointment-date"><strong>{new Date(`${item.localDate}T12:00:00`).toLocaleDateString("en",{day:"2-digit"})}</strong><span>{new Date(`${item.localDate}T12:00:00`).toLocaleDateString("en",{month:"short"})}</span></div><div className="appointment-info"><div><span className={`status-badge status-${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span><h2>{item.doctor.fullName}</h2><p>{item.doctor.specialization}</p></div><div className="appointment-facts"><span><CalendarClock/> {item.localDate} · {item.localStartTime}–{item.localEndTime}</span><span><MapPin/> {item.doctor.consultationLocation}</span></div></div><div className="appointment-actions">{item.canReschedule&&<button className="button button-secondary" onClick={()=>{setRescheduling(item);setDate(clinicToday());setSlot(null);}}><RotateCcw/>Reschedule</button>}{item.canCancel&&<button className="button danger-button" disabled={cancel.isPending} onClick={()=>{if(window.confirm("Cancel this appointment? The slot will become available to other patients."))cancel.mutate(item.id);}}><X/>Cancel</button>}{!item.canCancel&&["PENDING","CONFIRMED"].includes(item.status)&&<small>Changes close two hours before the visit.</small>}</div>{item.status==="COMPLETED"&&<div className="visit-note-card"><strong>Visit Note</strong><p>{item.visitNote?.note??"No visit note has been added yet."}</p></div>}</article>)}</div>
    {rescheduling&&<div className="modal-backdrop" role="dialog" aria-modal="true"><section className="reschedule-modal glass-panel"><button className="modal-close" aria-label="Close" onClick={()=>setRescheduling(null)}><X/></button><p className="modal-kicker">Reschedule with the same doctor</p><h2>{rescheduling.doctor.fullName}</h2><div className="current-time">Current: <strong>{rescheduling.localDate} · {rescheduling.localStartTime}</strong></div><label>New date<input type="date" min={clinicToday()} value={date} onChange={e=>{setDate(e.target.value);setSlot(null);}}/></label>{availability.isLoading?<div className="slot-loading">Checking availability…</div>:<div className="slots-grid">{availability.data?.slots.map(item=><button key={item.startAt} className={slot===item.localTime?"selected":""} onClick={()=>setSlot(item.localTime)}>{item.localTime}</button>)}</div>}{availability.data?.slots.length===0&&<div className="state-card">No free times on this date.</div>}{slot&&<div className="selection-note">New: <strong>{date} · {slot}</strong></div>}<button className="button button-primary modal-submit" disabled={!slot||move.isPending} onClick={()=>move.mutate()}>{move.isPending?"Rescheduling…":"Confirm new time"}</button></section></div>}
  </div>;
}
